### ISSUE TITLE
CancelApproval.js

### ISSUE THREAD

**Issue by lkzwieder** [Ingenico-ePayments/connect-sdk-nodejs#3]
You are calling cancelapproval but your files are named CancelApproval..

I'm pretty sure you are using Windows and it works for you because in windows lowercase or uppercase it is the same, is not the same in Linux.

![cancelapproval](https://cloud.githubusercontent.com/assets/757326/19623046/2324b24e-9891-11e6-8524-4535a87788ba.png)
![cancelapproval2](https://cloud.githubusercontent.com/assets/757326/19623057/5c73c9f4-9891-11e6-98df-0be06ad7cf26.png)

**Comment by lkzwieder** [comment]
The same occurs with ApproveSepaDirectdebit

**Comment by lkzwieder** [comment]
with Cards in riskassessments

**Comment by lkzwieder** [comment]
in Bankaccounts

**Comment by lkzwieder** [comment]
-.-

And there are a lot of similar files through all the app... I bet you are a JAVA developer..

**Comment by ebomcke-ingenico** [comment]
Good find, we'll check the entire repo and fix this issue.

**Comment by lkzwieder** [comment]
Thanks!!, can I fork and suggest you (via pull request) some modifications? If you allow me I will do that after I finish the implementation?

**Comment by ebomcke-ingenico** [comment]
Of course, you're welcome to do this. We'll review the suggested changes and update the code generation tools if needed to include them.
Btw, if you're at Money2020 come and see us, we'd love to meet you in person ! Plus we still have loads of water bottles :)

**Comment by lkzwieder** [comment]
Sadly I'm in Buenos Aires working on saturday night... I want to finish my 'garage company' as soon as possible. =)

**Comment by ebomcke-ingenico** [comment]
Haha, too bad then. Good luck, we'll be online for the next 16h or so as there's a hackathon going on so feel free to get in touch if you have other issues.
