### ISSUE TITLE
Sepa payment capture

### ISSUE THREAD

**Issue by SteveYon** [Ingenico-ePayments/connect-sdk-nodejs#5]
The directDebitText field is not mandatory for the 771 payment, so I'm having problems.
I can not create a payment without, and with I also receive an error message.
The only solution I found was to remove the required field 'directDebitText' from the SDK schema.

Can you solve the problem, we have been stuck for a while, the help channel could not give me the right answer.

edit: my json request has already been validated by the support

**Comment by rob-spoor** [comment]
Can you show the request and the error message that you received?

**Comment by SteveYon** [comment]
`{
"order": {
"amountOfMoney": {
"currencyCode": "EUR",
"amount": 2980
},
"customer": {
"merchantCustomerId": "1234",
"personalInformation": {
"name": {
"title": "Mr.",
"firstName": "Wile",
"surnamePrefix": "E.",
"surname": "Coyote"
},
"gender": "male",
"dateOfBirth": "19490917"
},
"companyInformation": {
"name": "Acme Labs"
},
"languageCode": "en",
"billingAddress": {
"street": "Desertroad",
"houseNumber": "13",
"additionalInfo": "b",
"zip": "84536",
"city": "Monument Valley",
"state": "Utah",
"countryCode": "US"
},
"shippingAddress": {
"name": {
"title": "Miss",
"firstName": "Road",
"surname": "Runner"
},
"street": "Desertroad",
"houseNumber": "1",
"additionalInfo": "Suite II",
"zip": "84536",
"city": "Monument Valley",
"state": "Utah",
"countryCode": "US"
},
"contactDetails": {
"emailAddress": "wile.e.coyote@acmelabs.com",
"phoneNumber": "+1234567890",
"faxNumber": "+1234567891",
"emailMessageType": "html"
},
"vatNumber": "1234AB5678CD"
},
"references": {
"merchantOrderId": "123456",
"merchantReference": "AcmeOrder0001",
"invoiceData": {
"invoiceNumber": "000000123",
"invoiceDate": "20140306191500"
},
"descriptor": "Fast and Furry-ous"
},
"items": [
{
"amountOfMoney": {
"currencyCode": "EUR",
"amount": 2500
},
"invoiceData": {
"nrOfItems": "1",
"pricePerItem": 2500,
"description": "ACME Super Outfit"
}
},
{
"amountOfMoney": {
"currencyCode": "EUR",
"amount": 480
},
"invoiceData": {
"nrOfItems": "12",
"pricePerItem": 40,
"description": "Asperin"
}
}
]
},
"sepaDirectDebitPaymentMethodSpecificInput": {
"paymentProductId": 771,
"paymentProduct771SpecificInput": {
"mandate": {
"customerReference":"userID",
"customer":{
"bankAccountIban":{
"iban":"FR1420041010050500013M02606"
},
"mandateAddress":{
"city":"le havre",
"countryCode": "FR",
"houseNumber":"2",
"street":"Quai",
"zip":"76600"
},
"personalInformation":{
"name":{
"firstName":"firstName",
"surname":"Surname"
},
"title":"Mr"
}
},
"recurrenceType":"RECURRING",
"returnUrl":"OUR_URL",
"signatureType":"UNSIGNED"
}
}
}
}`
Without directDebitText, the normal way, this error is returned
Error: instance.sepaDirectDebitPaymentMethodSpecificInput requires property "directDebitText"

With directDebitText:
Error: instance.sepaDirectDebitPaymentMethodSpecificInput requires property "directDebitText",instance.sepaDirectDebitPaymentMethodSpecificInput additionalProperty "directDebiText" exists in instance when not allowed

**Comment by rob-spoor** [comment]
I think the last error is caused by a typo - you have specified `directDebiText` instead of `directDebitText`.

However, I think I see the actual problem. The JSON schema (`schemas/payment/CreatePaymentRequest.json`) specifies that `sepaDirectDebitPaymentMethodSpecificInput.directDebitText` is required. However, for payment product 771, it is not allowed. This leads to a situation where it is not possible to pay with payment product 771.

We need to see how we can best solve this. Maybe we need to remove the requiredness from the JSON schemas, and let the requiredness validation occur only on the server. We need to see what the best way of going forward is.

**Comment by SteveYon** [comment]
I agree with the typo, I had not realized before.

Thus I was able to create a payment by removing the obligation on the sdk json schema.

Thanks for the support, let me know when a solution will be chosen

**Comment by rob-spoor** [comment]
We've just released a new version that does not mark any properties as required in the JSON schemas. It should now be possible to create payments with payment product 771.
